### ISSUE TITLE
GUI Link Broken?

### ISSUE THREAD

**Issue by JunjieLeiCoe** [KinesisCorporation/Adv360-Pro-ZMK#183] opened 2023-07-08 19:54 UTC
> https://kinesiscorporation.github.io/Adv360-Pro-GUI  

Is the GUI version link broken?

**Comment by ReFil** [comment] 2023-07-08 19:55
That link seems to work for me, what issue are you encountering?

**Comment by JunjieLeiCoe** [comment] 2023-07-08 23:02
The error message was related to `Unsecure Connections`, which I think might be related by the Chrome SSL certifications.

**Comment by ReFil** [comment] 2023-07-09 15:09
Which version of chrome and which operating system? I am unable to replicate this issue with several versions of chrome on android and linux

**Comment by leonnardo** [comment] 2023-07-12 06:43
Same here
Chrome 114.0.5735.199 on Windows 11

**Comment by JunjieLeiCoe** [comment] 2023-07-17 04:36
```
ERR_SSL_PROTOCOL_ERROR

```
Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by ashafaei** [comment] 2023-07-21 03:05
I had the same issue. turns out the URL is blocked by my firewall. if you visit the HTTP version, you'd know if it is being intercepted or not.

**Comment by KinesisCorporation** [comment] 2023-07-25 14:54
Sorry to hear you are having problems. The SSL certificate is issued to Github and it's not expired. Perhaps its a browser setting. Working fine here.

<img width="693" alt="image" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/37431414/dfd85a47-7026-4dfb-9ada-a87f1db7c48b">

**Comment by ashafaei** [comment] 2023-07-25 16:31
the issue is not the SSL certificate. for some reason, the firewall doesn't allow access to the URL and tries to intercept the connection. But since it can't/won't impersonate the destination, we end up getting SSL errors.

**Comment by ashafaei** [comment] 2023-07-25 17:06
when I access the url on `http` so that the interception works, this is what I get 
<img width="840" alt="Screenshot 2023-07-25 at 10 03 34 AM" src="https://github.com/KinesisCorporation/Adv360-Pro-ZMK/assets/3754799/aed5a2d7-3c72-49d5-98d2-3a75e3319424">
the question is why is it being blacklisted. the solution is changing your network or tunnelling your traffic through a node outside your network, or just disable any firewall in the middle temporarily.

**Comment by ReFil** [comment] 2023-07-25 17:14
That indicates it's a firewall on your ASUS router that's causing the problem, not anything on the remote side. Have you tried accessing the site using 4g on your phone?

**Comment by ashafaei** [comment] 2023-07-25 18:25
I already sorted it out. I'm just explaining why some people might experience this problem. Asus is outsourcing their blacklist to TrendMicro, https://global.sitesafety.trendmicro.com/result.php and if they have automatically blacklisted the page, the chances are that other firewalls do it too. the firewalls try to intercept your connection, and then the browser complains about the certificate.

**Comment by ReFil** [comment] 2023-07-25 20:22
Ok, thanks for the explanation. I'm going to close the issue as solved l

**Closed as completed by ReFil** 2023-07-25 20:22 UTC
