### ISSUE TITLE
V2.0 version

### ISSUE THREAD

**Issue by GGuinea** [KinesisCorporation/Adv360-Pro-ZMK#364] opened 2024-01-31 11:02 UTC
Hi!

After updating to V3.0 I'm struggling with communication problems between keyboard and newest macbook pro Sonoma 14.2.1. I want to rollback to old v2.0 version where everything was fine. Where Can I find old tag?

**Comment by ReFil** [comment] 2024-01-31 11:03
I would recommend you try this change: https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/104#issuecomment-1896681556

**Comment by huber-th** [comment] 2024-01-31 16:22
I had this issue as well where connection would randomly drop to my MacBook running latest Sonoma.

No drops since changing `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y` to `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n` in `adv360_left_defconfig` and `adv360_right_defconfig`

**Comment by asilvam133** [comment] 2024-01-31 18:14
Hi @ReFil. I applied the change you recommended and it worked.
Will this be fixed?

I notice that since the upgrade my keyboard connects to my Macbook as soon as it turns on, so that is a huge win and I was wondering if that new behavior is part of that feature being enabled?

**Comment by ReFil** [comment] 2024-01-31 18:18
This is a known bug currently. The fix for #278 can lead to connectivity issues on macOS. This will be addressed in a future update

**Comment by ReFil** [comment] 2024-02-06 17:05
Just following up on this, did those configuration changes rectify the issues you're having?

**Comment by GGuinea** [comment] 2024-02-06 17:06
I've tested it extensively and it helps. 
@ReFil should I close this issue? Maybe it should be open since it's not only my problem and probably it would be easier to find fix for other users

**Comment by kbumsik** [comment] 2024-03-01 10:29
I have two Adv360 keyboards and both had exactly the same issue after upgrading.

I also confirm that setting `CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n` fixes the issue on both keyboards!

**Comment by ztomer** [comment] 2024-03-13 17:54
I can confirm to also experience this issue on an M1 Macbook Pro with Sonoma 14.4. 
With CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

**Comment by ReFil** [comment] 2024-04-15 11:19
This should now be rectified with the latest update

**Closed as completed** 2024-04-15 11:24 UTC

**Comment by kbumsik** [comment] 2024-04-16 18:54
I applied the new update to two Adv360s for a day right after the release.
I report that I have no such issue for a day!
